spring.application.name=review-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/review_platform
spring.datasource.username=vanshraj
spring.datasource.password=abcd123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
